### PR TITLE
feat: Controlling property name generation

### PR DESCRIPTION
**Pull request by richardschneider**
PR for #15 

- fix removing 'Is' from property name
- add POCOOptions to control property name generation

### CODE REVIEW

**Comment by peteroupc** [comment]
The approach you took with POCOOptions is not ideal, since it involves global state.  A better idea might be to add a new method to CBORObject or add a new CBOREncodeOptions option.  However, you did identify a bug on removing "Is".  I will incorporate that fix

**Comment by richardschneider** [comment]
@peteroupc I agree, global options is not great. As I [commented](https://github.com/peteroupc/CBOR/issues/15#issuecomment-392224396) passing options to `GetPropertyList` would require a lot of changes.

**Comment by richardschneider** [comment]
`GetPropertyList` maintains a static cache for each property name of a type.  Therefore, options to control property name generation ,must be 'global' or name generation becomes inconsistent.

**Comment by richardschneider** [comment]
Another approach is being implemented, see https://github.com/peteroupc/CBOR/issues/15#issuecomment-398252958.

**Pull request closed without merging**
