### PR TITLE
Apply code suggestions and formatting from VS2022

### PR DESCRIPTION
**Pull request by charlesroddie**
- Apply code suggestions and formatting from VS2022 with default settings
- Add an editorconfig file based on these settings

The changes are very good in my opinion and as an F# user I find the code analysis that C# users get is pretty nice.

The diff is huge because of the auto-formatting so this would mess with any other active branches if any. Formatting rules could be changed in .editorconfig to reduce this diff.

Fixes https://github.com/peteroupc/CBOR/issues/62

### CODE REVIEW

**Comment by peteroupc** [comment]
You should update this pull request with `indent_size = 2` and `csharp_indent_braces = true`, and in general any other formatting rule that minimizes the size of this pull request.

**Comment by charlesroddie** [comment]
I assume the current formats are based on customization on your system? Can you export an .editorconfig file for this? For example from VS via https://stackoverflow.com/a/56954297/4903561 . That would allow me and others to contribute to the project. Currently if you for example delete a closing curly bracket and re-add it, a large and incompatible formatting change results since VS assumes standard formatting.

**Comment by peteroupc** [comment]
I have created an `.editorconfig` with the changes `indent_size = 2`, `tab_width = 2`, and `dotnet_diagnostic.SA1210.severity = none` (to disable enforcing alphabetical order on `using` directives).  Rebase this pull request with these changes, please.

**Comment by charlesroddie** [comment]
Redone PR in https://github.com/peteroupc/CBOR/pull/67

**Pull request closed without merging**
